Drop DATABASE IF EXISTS VCs;

CREATE DATABASE VCs;

USE VCs;

CREATE TABLE VCs(
   VID VARCHAR(256) NOT NULL PRIMARY KEY,
   VC_NAME VARCHAR (256) NOT NULL,
   PERMA_LINK  VARCHAR(256) NOT NULL,
   IMAGE  VARCHAR (256) ,
   DESCRIPTION VARCHAR (6000),
   URL VARCHAR (256),
   UUID VARCHAR(256) NOT NULL,
   ADDRESS VARCHAR (256),
   CITY VARCHAR (256),
   ZIPCODE VARCHAR(256) ,
   STATE VARCHAR (10)
);

CREATE TABLE COMPANIES(
   CID VARCHAR(256) NOT NULL PRIMARY KEY,
   COMPANY_NAME VARCHAR (256) NOT NULL,
   PERMA_LINK  VARCHAR(256) NOT NULL,
   IMAGE VARCHAR (256) ,
   DESCRIPTION VARCHAR (6000),
   URL VARCHAR (256),
   UUID VARCHAR(256) NOT NULL,
   TOTAL_FUNDING VARCHAR(256)
);

CREATE TABLE VC_COMPANY(
   VID VARCHAR(256) NOT NULL ,
   FOREIGN KEY (VID) REFERENCES VCs(VID),
   VC_NAME VARCHAR(256) NOT NULL,
   CID VARCHAR(256) NOT NULL ,
   FOREIGN KEY (CID) REFERENCES COMPANIES(CID),
   COMPANY_NAME VARCHAR (256) NOT NULL
);
