Drop DATABASE IF EXISTS VENTURE;

CREATE DATABASE VENTURE;

USE VENTURE;

CREATE TABLE VCs(
   VID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
   VC_NAME VARCHAR (256) NOT NULL,
   PERMA_LINK  VARCHAR(256) NOT NULL,
   IMAGE  VARCHAR (256) ,
   DESCRIPTION VARCHAR (256),
   URL VARCHAR (256),
   UUID INT NOT NULL,
   ADDRESS VARCHAR (256),
   CITY VARCHAR (256),
   ZIPCODE INT ,
   STATE CHAR (10)
);

CREATE TABLE COMPANIES(
   CID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
   COMPANY_NAME VARCHAR (256) NOT NULL,
   PERMA_LINK  VARCHAR(256) NOT NULL,
   IMAGE VARCHAR (256) ,
   DESCRIPTION VARCHAR (256),
   URL VARCHAR (256),
   UUID INT NOT NULL,
   TOTAL_FUNDING FLOAT
);

CREATE TABLE VC_COMPANY(
   VID INT NOT NULL,
   FOREIGN KEY (VID) REFERENCES VCs(VID),
   CID INT NOT NULL,
   FOREIGN KEY (CID) REFERENCES COMPANIES(CID)
);
