CREATE TABLE VCs(
   VID   INT              			  NOT NULL,
   VC_NAME VARCHAR (256)    		  NOT NULL,
   PERMA_LINK  VARCHAR(256)           NOT NULL,
   IMAGE  VARCHAR (256) ,
   DESCRIPTION   VARCHAR (256),       
   URL VARCHAR (256),
   UUID INT 						  NOT NULL,
   ADDRESS VARCHAR (256), 
   CITY VARCHAR (256),
   ZIPCODE INT ,
   STATE CHAR (10),
   PRIMARY KEY (VID),
   FOREIGN KEY (VID) REFERENCES VC_COMPANY(VID)
);


CREATE TABLE COMPANIES(
   CID   INT              		NOT NULL,
   COMPANY_NAME VARCHAR (256)   NOT NULL,
   PERMA_LINK  VARCHAR(256)     NOT NULL,
   IMAGE  VARCHAR (256) ,
   DESCRIPTION   VARCHAR (256),       
   URL VARCHAR (256),
   UUID INT 					NOT NULL,
   TOTAL_FUNDING FLOAT,
   PRIMARY KEY (CID),
   FOREIGN KEY (CID) REFERENCES VC_COMPANY(CID)
);


CREATE TABLE VC_COMPANY(
   VID   INT              NOT NULL,
   CID   INT			  NOT NULL, 
);